S3DirectWebsite/Core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "Public"
urlpatterns = [
     path("", Home.home, name = "HomePageReverse"),
     path("home/", Home.home, name = "HomePage"),
     path("about/", Home.about, name = "AboutPage"),
     path("contact/", Home.contact, name = "ContactPage"),
     path("download/", Home.download, name = "DownloadPage"),

     path("forum/", Forum.forum, name = "ForumPage"),
     path("forum/create/", Forum.forumCreate, name = "ForumCreatePage"),
     path("forum/<str:slug>/", Forum.forumDetail, name = "ForumDetailPage"),
     path("forum/<str:slug>/action/", Forum.forumAction, name = "ForumActionPage"),
     path("forum/<str:slug>/edit/", Forum.forumEdit, name = "ForumEditPage"),
     path("forum/<str:slug>/delete/", Forum.forumDelete, name = "ForumDeletePage"),
     path("forum/<str:slug>/comment/", Forum.forumComment, name = "ForumAddComment"),

     path("reviews/", ReviewsC.reviewsFunc, name = "ReviewsPage"),
     path("reviews/update/", ReviewsC.reviewsUpdate, name = "ReviewsUpdatePage"),
]

S3DirectWebsite/S3DirectWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('auth/', include('Authenticate.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

S3DirectWebsite/Core/views/Forum.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authenticate.models import *
from Core.models import *
import os

def forum(request):
    if request.method == 'GET':
        sortby = request.GET.get('sortby')
        if sortby == 'ascdate':
            sortby = 'dateCreated'
        elif sortby == 'dscdate':
            sortby = '-dateCreated'
        elif sortby == 'mcomments':
            sortby = '-CommentsCount'
        elif sortby == 'mliked':
            sortby = '-UpvotesCount'
        else:
            sortby = '-dateCreated'

        Forums = Post.objects.filter().order_by(sortby)
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "Forums": Forums
            }
        else:
            context = {
                "isAuthenticated": False,
                "Forums": Forums
            }
        return render(request, 'Public/Forum/Forum.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumCreate(request):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        if request.method == 'POST':
            Title = request.POST.get('Title')
            Content = request.POST.get('Content')
            _Attachments = request.FILES.getlist('Attachments')
            
            _Post = Post.objects.create(Profile = _Account, Title = Title, Content = Content)
            Segments, Slug = Title.split(' '), f'{_Account.Username}-'
            for Segment in Segments:
                Slug += Segment.lower() + '-'
            Slug += str(_Post.primaryKey)
            _Post.slug = Slug
            _Post.save()

            for attachment in _Attachments:
                _Attachment = Attachments.objects.create(Profile = _Account, File = attachment, Type = os.path.splitext(attachment.name)[1])
                _Post.Attachments.add(_Attachment)
                _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumPage'))
        else:
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
            return render(request, 'Public/Forum/ForumCreate.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
        
def forumDetail(request, slug):
    if request.method == 'GET':
        _Post = Post.objects.get(slug = slug)
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)

            userComment = Comment.objects.filter(Profile = _Account, Post = _Post).first()
            Commented = Comment.objects.filter(Profile = _Account, Post = _Post).exists()
            Liked = _Post.Upvotes.filter(Username = _Account.Username).exists()
            Disliked = _Post.Downvotes.filter(Username = _Account.Username).exists()
            Comments = Comment.objects.filter(Post = _Post).exclude(Profile = _Account).order_by('-dateCreated')

            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "Post": _Post,
                "Comments": Comments,
                "UserComment": userComment,
                "Commented": Commented,
                "Liked": Liked,
                "Disliked": Disliked,
            }
        else: 
            Comments = Comment.objects.filter(Post = _Post).order_by('-dateCreated')
            context = {
                "isAuthenticated": False,
                "Post": _Post,
                "Comments": Comments
            }
        return render(request, 'Public/Forum/ForumDetail.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumComment(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST':
            Content = request.POST.get('Content')
            _Attachments = request.FILES.getlist('Attachments')

            if Comment.objects.filter(Profile = _Account, Post = _Post).exists():
                Comment.objects.filter(Profile = _Account, Post = _Post).delete()
                _Post.CommentsCount -= 1
                _Post.save()
            
            _Comment = Comment.objects.create(Profile = _Account, Post = _Post, Content = Content)
            for attachment in _Attachments:
                _Attachment = Attachments.objects.create(Profile = _Account, File = attachment, Type = os.path.splitext(attachment.name)[1])
                _Comment.Attachments.add(_Attachment)
                _Comment.save()
            _Post.CommentsCount += 1
            _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
        else:
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumEdit(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST' and _Post.Profile.Username == _Account.Username:
            Title = request.POST.get('Title')
            Content = request.POST.get('Content')
            _Attachments = request.FILES.getlist('Attachments')
            
            _Post.Title = Title
            _Post.Content = Content
            _Post.Attachments.clear()
            _Post.save()

            for attachment in _Attachments:
                _Attachment = Attachments.objects.create(Profile = _Account, File = attachment, Type = os.path.splitext(attachment.name)[1])
                _Post.Attachments.add(_Attachment)
                _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
        else:
            if _Post.Profile.Username == _Account.Username:
                context = {
                    "isAuthenticated": True,
                    "Account": _Account,
                    "Post": _Post
                }
                return render(request, 'Public/Forum/ForumEdit.html', context)
            else:
                return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumAction(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST':
            Action = request.POST.get('Action')
            if Action == 'Upvote':
                if _Post.Downvotes.filter(Username = _Account.Username).exists():
                    _Post.Downvotes.remove(_Account)
                    _Post.DownVotesCount -= 1
                    _Post.save()

                if _Post.Upvotes.filter(Username = _Account.Username).exists():
                    _Post.Upvotes.remove(_Account)
                    _Post.UpvotesCount -= 1
                    _Post.save()
                else:
                    _Post.Upvotes.add(_Account)
                    _Post.UpvotesCount += 1
                    _Post.save()
            elif Action == 'Downvote':
                if _Post.Upvotes.filter(Username = _Account.Username).exists():
                    _Post.Upvotes.remove(_Account)
                    _Post.UpvotesCount -= 1
                    _Post.save()

                if _Post.Downvotes.filter(Username = _Account.Username).exists():
                    _Post.Downvotes.remove(_Account)
                    _Post.DownVotesCount -= 1
                    _Post.save()
                else:
                    _Post.Downvotes.add(_Account)
                    _Post.DownVotesCount += 1
                    _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
        else:
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumDelete(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST':
            if _Post.Profile.Username == _Account.Username:
                _Post.delete()
            return HttpResponseRedirect(reverse('Public:ForumPage'))
        else:
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))

S3DirectWebsite/Core/views/Home.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authenticate.models import *
from Core.models import *

def home(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }

        reqReviews = Reviews.objects.order_by('-dateCreated')[:3]
        context["Reviews"] = reqReviews
        return render(request, 'Public/Pages/Home.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))
    
def about(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }
        return render(request, 'Public/Pages/About.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))

def contact(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }
        return render(request, 'Public/Pages/Contact.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))
    
def download(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }

        reqReviews = Reviews.objects.order_by('-dateCreated')[:3]
        context["Reviews"] = reqReviews
        return render(request, 'Public/Pages/Download.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))

S3DirectWebsite/Core/views/ReviewsC.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authenticate.models import *
from Core.models import *

def reviewsFunc(request):
    if request.method == 'GET':
        sortby, Param = str(request.GET.get('sortby')), None
        if sortby.endswith('date'):
            if sortby.startswith('asc'):
                Param = 'dateCreated'
            else:
                Param = '-dateCreated'
        else:
            if sortby.startswith('asc'):
                Param = 'Rating'
            else:
                Param = '-Rating'

        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            UserReviews = Reviews.objects.filter(Profile = _Account).first()
            _Reviews = Reviews.objects.exclude(Profile = _Account).order_by(Param)

            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "UserReviews": UserReviews,
                "Reviews": _Reviews
            }

        else:
            _Reviews = Reviews.objects.all().order_by(Param)
            context = {
                "isAuthenticated": False,
                "Reviews": _Reviews
            }
        return render(request, 'Public/Reviews/Reviews.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ReviewsPage'))
    
def reviewsUpdate(request):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        if request.method == 'POST':
            Content = request.POST.get('Content')
            Rating = int(request.POST.get('Rating'))

            UserReviews = Reviews.objects.filter(Profile = _Account).first()
            if UserReviews:
                UserReviews.Content = Content
                UserReviews.Rating = Rating
                UserReviews.save()
            else:
                UserReviews = Reviews.objects.create(Profile = _Account, Content = Content, Rating = Rating)
                UserReviews.save()
            return HttpResponseRedirect(reverse('Public:ReviewsPage'))
        else:
            _Reviews = Reviews.objects.filter(Profile = _Account).first()
            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "Reviews": _Reviews
            }
            return render(request, 'Public/Reviews/ReviewsUpdate.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ReviewsPage'))

S3DirectWebsite/Core/templates/Public/Forum/Forum.html
{% extends 'Core.html' %}

{% block headSection %}
<link rel="stylesheet" href="/static/forumstyle.css">
{% endblock %}

{% block content %}

  <div class="container">

    {% if isAuthenticated %}
      <button class="create-post-btn">Create a post</button>
    {% endif %}

    <label for="options">Sort by:</label>
    <select id="options" onchange="window.location.href = this.value;">
        <option value="" selected disabled>Choose an option</option>
        <option value="{% url 'Public:ForumPage' %}?sortby=ascdate">Asc dateCreated</option>
        <option value="{% url 'Public:ForumPage' %}?sortby=dscdate">Dsc dateCreated</option>
        <option value="{% url 'Public:ForumPage' %}?sortby=mcomments">Most Comments</option>
        <option value="{% url 'Public:ForumPage' %}?sortby=mliked">Most Liked</option>
    </select>

      <div class="post-list">

        {% for post in Forums %}

          <div class="post">
              <h3 class="username">{{ post.Profile.Username }}</h3>
              <a href="{% url 'Public:ForumDetailPage' post.slug %}" class="post-title">{{ post.Title }}</h2></a>
              <p>{{ post.Content }}</p>
              {% if post.Attachments.first %}
                {% for attachment in post.Attachments.all %}
                  <img src="{{ attachment.File.url }}" width="100" height="100"/>
                {% endfor %}
              {% endif %}
              <div class="post-actions">
                  <a href="{% url 'Public:ForumDetailPage' post.slug %}">
                      <span class="upvote-count">{{ post.UpvotesCount }}</span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                      <path fill="currentColor"
                          d="M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625zM15 12h-1v8h-4v-8H6.081L12 4.601L17.919 12z" />
                      </svg>
                    </a>
                  <button href="{% url 'Public:ForumDetailPage' post.slug %}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                      <path fill="currentColor"
                          d="M6 14h12v-2H6zm0-3h12V9H6zm0-3h12V6H6zM4 18q-.825 0-1.412-.587T2 16V4q0-.825.588-1.412T4 2h16q.825 0 1.413.588T22 4v18l-4-4z" />
                      </svg>
                  </button>
                  <button>
                      <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                      <path fill="currentColor"
                          d="M18 22q-1.25 0-2.125-.875T15 19q0-.175.025-.363t.075-.337l-7.05-4.1q-.425.375-.95.588T6 15q-1.25 0-2.125-.875T3 12t.875-2.125T6 9q.575 0 1.1.213t.95.587l7.05-4.1q-.05-.15-.075-.337T15 5q0-1.25.875-2.125T18 2t2.125.875T21 5t-.875 2.125T18 8q-.575 0-1.1-.212t-.95-.588L8.9 11.3q.05.15.075.338T9 12t-.025.363t-.075.337l7.05 4.1q.425-.375.95-.587T18 16q1.25 0 2.125.875T21 19t-.875 2.125T18 22" />
                      </svg>
                  </button>
              </div>
          </div>

          {% endfor %}

          <div id="post-modal" class="modal">
            <form action="{% url 'Public:ForumCreatePage' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="modal-content">
                  <span class="close-btn">&times;</span>
                  <input class="create-post-title" type="text" placeholder="Title" type="text" id="title" name="Title" required>
                  <textarea placeholder="Write a post" id="content" name="Content"></textarea>
                  <input type="file" id="Attachments" name="Attachments" accept="image/*" multiple>
                  <button class="post-btn" type="submit">Post</button>
              </div>
            </form>
          </div>

          <script src="/static/forumscript.js"></script>

{% endblock %}

S3DirectWebsite/Core/templates/Public/Forum/ForumDetail.html
{% extends 'Core.html' %}

{% block headSection %}
<link rel="stylesheet" href="/static/forumstyle.css">
<link rel="stylesheet" href="/static/forumpoststyle.css">
{% endblock %}

{% block content %}
<!-- 
  <h1>Forum Thread</h1>
  {% if isAuthenticated %}
  <button><a href="{% url 'Public:ForumEditPage' Post.slug %}">Edit</a></button>
  {% endif %}
  {% if isAuthenticated %}
  <form action="{% url 'Public:ForumDeletePage' Post.slug %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
  </form>
  {% endif %}

    <hr/>
    <h2>{{ Post.Title }}</h2>
    <p>{{ Post.Content }}</p>
    <p>By: {{ Post.Profile.Username }}</p>
    <p>Created: {{ Post.dateCreated }}</p>
    <p>Updated: {{ Post.dateModified }}</p>

    {% if Post.Attachments.first %}
      <p>Attachments:</p>
      {% for attachment in Post.Attachments.all %}
        <img src="{{ attachment.File.url }}" width="100" height="100"/>
      {% endfor %}
    {% endif %}

    <br/><br/>

    {% if isAuthenticated %}
      <form action="{% url 'Public:ForumActionPage' Post.slug %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="Action" value="Upvote">
        {{ Post.UpvotesCount }}
        <input type="submit" value="Upvote">
      </form>

      <form action="{% url 'Public:ForumActionPage' Post.slug %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="Action" value="Downvote">
        {{ Post.DownVotesCount }}
        <input type="submit" value="Downvote">
      </form>
    {% else %}
      {{ Post.UpvotesCount }} - Upvotes
      {{ Post.DownVotesCount }} - Downvotes
    {% endif %}

    {{ Post.CommentsCount }} - Comments

    <hr/>

    <h2>Comments</h2>
    
    {% if isAuthenticated %}

      <p>
        {% if Commented %}
          Edit your comment
        {% else %}
          Add Comment
        {% endif %}
      </p>

      <form action="{% url 'Public:ForumAddComment' Post.slug %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="content">Content:</label>

        {% if Commented %}
          <textarea id="content" name="Content" rows="5" cols="50" required>{{ UserComment.Content }}</textarea>
        {% else %}
          <textarea id="content" name="Content" required></textarea>
        {% endif %}

        <input type="file" id="Attachments" name="Attachments" accept="image/*" multiple>
        <br><br/>
        {% if Commented %}
          <input type="submit" value="Edit Comment">
        {% else %}
          <input type="submit" value="Add Comment">
        {% endif %}
      </form>

      {% if UserComment.Attachments.first %}
        <p>Attachments:</p>
        {% for attachment in UserComment.Attachments.all %}
          <img src="{{ attachment.File.url }}" width="100" height="100"/>
        {% endfor %}
      {% endif %}

      <hr/>

    {% else %}
      <h4>Login to post your comments</h4>
    {% endif %}

    {% for comment in Comments %}
      <hr/>
      <p>{{ comment.Content }}</p>
      <p>By: {{ comment.Profile.Username }}</p>
      <p>Created: {{ comment.dateCreated }}</p>
      <p>Updated: {{ comment.dateModified }}</p>

      {% if comment.Attachments.first %}
        <p>Attachments:</p>
        {% for attachment in comment.Attachments.all %}
          <img src="{{ attachment.File.url }}" width="100" height="100"/>
        {% endfor %}
      {% endif %}

      <br/><br/>

      {% if comment.Profile.Username|lower == Account.Username|lower %}
      <button><a href="{% url 'Public:ForumPage' %}">Edit</a></button>
      <button><a href="{% url 'Public:ForumPage' %}">Delete</a></button>
      {% endif %}

      <hr/>
      <br/><br/>
    {% empty %}
      <h4>No Comments found.</h4>
    {% endfor %} -->


    <div class="post-container">
        <div class="post">
              <div class="post-author">{{ Post.Profile.Username }}</div>
              <div class="post-header">{{ Post.Title }}</div>
              <div class="post-content">{{ Post.Content }}</div>
              <div class="post-image">
                {% if Post.Attachments.first %}
                  {% for attachment in Post.Attachments.all %}
                    <img src="{{ attachment.File.url }}" width="100" height="100"/>
                  {% endfor %}
                {% endif %}
              </div>
              <div class="post-actions">
                  
                  <!-- <button href="{% url 'Public:ForumDetailPage' Post.slug %}">
                      <span class="upvote-count">{{ Post.UpvotesCount }}</span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                          <path fill="currentColor"
                              d="M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625zM15 12h-1v8h-4v-8H6.081L12 4.601L17.919 12z" />
                      </svg>
                  </button> -->


                  {% if isAuthenticated %}
                    <form action="{% url 'Public:ForumActionPage' Post.slug %}" method="post">
                      {% csrf_token %}
                      <input type="hidden" name="Action" value="Upvote">
                      <button type="submit">
                        <span class="upvote-count">{{ Post.UpvotesCount }}</span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                            <path fill="currentColor"
                                d="M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625zM15 12h-1v8h-4v-8H6.081L12 4.601L17.919 12z" />
                        </svg>
                      </button>
                    </form>
                  {% else %}
                  <button onclick="alert('Login to upvote.')">
                    <span class="upvote-count">{{ Post.UpvotesCount }}</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                        <path fill="currentColor"
                            d="M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625zM15 12h-1v8h-4v-8H6.081L12 4.601L17.919 12z" />
                    </svg>
                  </button>
                  {% endif %}

                  <button>
                      <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                          <path fill="currentColor"
                              d="M6 14h12v-2H6zm0-3h12V9H6zm0-3h12V6H6zM4 18q-.825 0-1.412-.587T2 16V4q0-.825.588-1.412T4 2h16q.825 0 1.413.588T22 4v18l-4-4z" />
                      </svg>
                  </button>
                  <button>
                      <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                          <path fill="currentColor"
                              d="M18 22q-1.25 0-2.125-.875T15 19q0-.175.025-.363t.075-.337l-7.05-4.1q-.425.375-.95.588T6 15q-1.25 0-2.125-.875T3 12t.875-2.125T6 9q.575 0 1.1.213t.95.587l7.05-4.1q-.05-.15-.075-.337T15 5q0-1.25.875-2.125T18 2t2.125.875T21 5t-.875 2.125T18 8q-.575 0-1.1-.212t-.95-.588L8.9 11.3q.05.15.075.338T9 12t-.025.363t-.075.337l7.05 4.1q.425-.375.95-.587T18 16q1.25 0 2.125.875T21 19t-.875 2.125T18 22" />
                      </svg>
                  </button>
              </div>
          </div>

          <div class="comments">
              <div class="add-comment">
                <form action="{% url 'Public:ForumAddComment' Post.slug %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}

                  {% if Commented %}
                    <input type="text"  id="content" name="Content"  placeholder="Add a comment" value="{{ UserComment.Content }}">
                  {% else %}
                    <input type="text"  id="content" name="Content" placeholder="Add a comment">
                  {% endif %}

                  <input type="file" id="Attachments" name="Attachments" accept="image/*" multiple hidden>
                  <input type="submit" hidden>

                </form>
              </div>

              {% if Commented %}
                <div class="comment">
                    <div class="comment-author">{{ UserComment.Profile.Username }}</div>
                    <div class="comment-content">{{ UserComment.Content }}</div>
                </div>
              {% endif %}

              {% for comment in Comments %}
              <div class="comment">
                  <div class="comment-author">{{ comment.Profile.Username }}</div>
                  <div class="comment-content">{{ comment.Content }}</div>
              </div>
              {% empty %}
                <h4>No Comments found.</h4>
              {% endfor %}
              
              <!-- Add more comments here -->
          </div>
      </div>

{% endblock %}