S3DirectWebsite/Authenticate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "Authenticate"
urlpatterns = [
    path("login/", auth.login, name = "LoginPage"),
    path("logout/", auth.logout, name = "LogoutPage"),
    path("create/account/", auth.createAccount, name = "CreateAccount"),
    path("account/forgot/password/", auth.forgotPassword, name = "ForgotPassword"),
]

S3DirectWebsite/Core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "Public"
urlpatterns = [
     path("", Home.home, name = "HomePageReverse"),
     path("home/", Home.home, name = "HomePage"),
     path("about/", Home.about, name = "AboutPage"),
     path("contact/", Home.contact, name = "ContactPage"),
     path("download/", Home.download, name = "DownloadPage"),

     path("forum/", Forum.forum, name = "ForumPage"),
     path("forum/create/", Forum.forumCreate, name = "ForumCreatePage"),
     path("forum/<str:slug>/", Forum.forumDetail, name = "ForumDetailPage"),
     path("forum/<str:slug>/action/", Forum.forumAction, name = "ForumActionPage"),
     path("forum/<str:slug>/edit/", Forum.forumEdit, name = "ForumEditPage"),
     path("forum/<str:slug>/delete/", Forum.forumDelete, name = "ForumDeletePage"),
     path("forum/<str:slug>/comment/", Forum.forumComment, name = "ForumAddComment"),

     path("reviews/", ReviewsC.reviewsFunc, name = "ReviewsPage"),
     path("reviews/update/", ReviewsC.reviewsUpdate, name = "ReviewsUpdatePage"),
]

S3DirectWebsite/S3DirectWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('auth/', include('Authenticate.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

S3DirectWebsite/Core/views/Forum.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authenticate.models import *
from Core.models import *
import os

def forum(request):
    if request.method == 'GET':
        sortby = request.GET.get('sortby')
        if sortby == 'ascdate':
            sortby = 'dateCreated'
        elif sortby == 'dscdate':
            sortby = '-dateCreated'
        elif sortby == 'mcomments':
            sortby = '-CommentsCount'
        elif sortby == 'mliked':
            sortby = '-UpvotesCount'
        else:
            sortby = '-dateCreated'

        Forums = Post.objects.filter().order_by(sortby)
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "Forums": Forums
            }
        else:
            context = {
                "isAuthenticated": False,
                "Forums": Forums
            }
        return render(request, 'Public/Forum/Forum.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumCreate(request):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        if request.method == 'POST':
            Title = request.POST.get('Title')
            Content = request.POST.get('Content')
            _Attachments = request.FILES.getlist('Attachments')
            
            _Post = Post.objects.create(Profile = _Account, Title = Title, Content = Content)
            Segments, Slug = Title.split(' '), f'{_Account.Username}-'
            for Segment in Segments:
                Slug += Segment.lower() + '-'
            Slug += str(_Post.primaryKey)
            _Post.slug = Slug
            _Post.save()

            for attachment in _Attachments:
                _Attachment = Attachments.objects.create(Profile = _Account, File = attachment, Type = os.path.splitext(attachment.name)[1])
                _Post.Attachments.add(_Attachment)
                _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumPage'))
        else:
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
            return render(request, 'Public/Forum/ForumCreate.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
        
def forumDetail(request, slug):
    if request.method == 'GET':
        _Post = Post.objects.get(slug = slug)
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)

            userComment = Comment.objects.filter(Profile = _Account, Post = _Post).first()
            Commented = Comment.objects.filter(Profile = _Account, Post = _Post).exists()
            Liked = _Post.Upvotes.filter(Username = _Account.Username).exists()
            Disliked = _Post.Downvotes.filter(Username = _Account.Username).exists()
            Comments = Comment.objects.filter(Post = _Post).exclude(Profile = _Account).order_by('-dateCreated')

            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "Post": _Post,
                "Comments": Comments,
                "UserComment": userComment,
                "Commented": Commented,
                "Liked": Liked,
                "Disliked": Disliked,
            }
        else: 
            Comments = Comment.objects.filter(Post = _Post).order_by('-dateCreated')
            context = {
                "isAuthenticated": False,
                "Post": _Post,
                "Comments": Comments
            }
        return render(request, 'Public/Forum/ForumDetail.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumComment(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST':
            Content = request.POST.get('Content')
            _Attachments = request.FILES.getlist('Attachments')

            if Comment.objects.filter(Profile = _Account, Post = _Post).exists():
                Comment.objects.filter(Profile = _Account, Post = _Post).delete()
                _Post.CommentsCount -= 1
                _Post.save()
            
            _Comment = Comment.objects.create(Profile = _Account, Post = _Post, Content = Content)
            for attachment in _Attachments:
                _Attachment = Attachments.objects.create(Profile = _Account, File = attachment, Type = os.path.splitext(attachment.name)[1])
                _Comment.Attachments.add(_Attachment)
                _Comment.save()
            _Post.CommentsCount += 1
            _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
        else:
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumEdit(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST' and _Post.Profile.Username == _Account.Username:
            Title = request.POST.get('Title')
            Content = request.POST.get('Content')
            _Attachments = request.FILES.getlist('Attachments')
            
            _Post.Title = Title
            _Post.Content = Content
            _Post.Attachments.clear()
            _Post.save()

            for attachment in _Attachments:
                _Attachment = Attachments.objects.create(Profile = _Account, File = attachment, Type = os.path.splitext(attachment.name)[1])
                _Post.Attachments.add(_Attachment)
                _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
        else:
            if _Post.Profile.Username == _Account.Username:
                context = {
                    "isAuthenticated": True,
                    "Account": _Account,
                    "Post": _Post
                }
                return render(request, 'Public/Forum/ForumEdit.html', context)
            else:
                return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumAction(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST':
            Action = request.POST.get('Action')
            if Action == 'Upvote':
                if _Post.Downvotes.filter(Username = _Account.Username).exists():
                    _Post.Downvotes.remove(_Account)
                    _Post.DownVotesCount -= 1
                    _Post.save()

                if _Post.Upvotes.filter(Username = _Account.Username).exists():
                    _Post.Upvotes.remove(_Account)
                    _Post.UpvotesCount -= 1
                    _Post.save()
                else:
                    _Post.Upvotes.add(_Account)
                    _Post.UpvotesCount += 1
                    _Post.save()
            elif Action == 'Downvote':
                if _Post.Upvotes.filter(Username = _Account.Username).exists():
                    _Post.Upvotes.remove(_Account)
                    _Post.UpvotesCount -= 1
                    _Post.save()

                if _Post.Downvotes.filter(Username = _Account.Username).exists():
                    _Post.Downvotes.remove(_Account)
                    _Post.DownVotesCount -= 1
                    _Post.save()
                else:
                    _Post.Downvotes.add(_Account)
                    _Post.DownVotesCount += 1
                    _Post.save()
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
        else:
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))
    
def forumDelete(request, slug):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        _Post = Post.objects.get(slug = slug)
        if request.method == 'POST':
            if _Post.Profile.Username == _Account.Username:
                _Post.delete()
            return HttpResponseRedirect(reverse('Public:ForumPage'))
        else:
            return HttpResponseRedirect(reverse('Public:ForumDetailPage', args = [slug]))
    else:
        return HttpResponseRedirect(reverse('Public:ForumPage'))

S3DirectWebsite/Core/views/Home.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authenticate.models import *
from Core.models import *

def home(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }

        reqReviews = Reviews.objects.order_by('-dateCreated')[:3]
        context["Reviews"] = reqReviews
        return render(request, 'Public/Pages/Home.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))
    
def about(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }
        return render(request, 'Public/Pages/About.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))

def contact(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }
        return render(request, 'Public/Pages/Contact.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))
    
def download(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            context = {
                "isAuthenticated": True,
                "Account": _Account
            }
        else:
            context = {
                "isAuthenticated": False
            }

        reqReviews = Reviews.objects.order_by('-dateCreated')[:3]
        context["Reviews"] = reqReviews
        return render(request, 'Public/Pages/Download.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:HomePage'))

S3DirectWebsite/Core/views/ReviewsC.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authenticate.models import *
from Core.models import *

def reviewsFunc(request):
    if request.method == 'GET':
        sortby, Param = str(request.GET.get('sortby')), None
        if sortby.endswith('date'):
            if sortby.startswith('asc'):
                Param = 'dateCreated'
            else:
                Param = '-dateCreated'
        else:
            if sortby.startswith('asc'):
                Param = 'Rating'
            else:
                Param = '-Rating'

        if request.user.is_authenticated:
            _Account = Account.objects.get(Username = request.user)
            UserReviews = Reviews.objects.filter(Profile = _Account).first()
            _Reviews = Reviews.objects.exclude(Profile = _Account).order_by(Param)

            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "UserReviews": UserReviews,
                "Reviews": _Reviews
            }

        else:
            _Reviews = Reviews.objects.all().order_by(Param)
            context = {
                "isAuthenticated": False,
                "Reviews": _Reviews
            }
        return render(request, 'Public/Reviews/Reviews.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ReviewsPage'))
    
def reviewsUpdate(request):
    if request.user.is_authenticated:
        _Account = Account.objects.get(Username = request.user)
        if request.method == 'POST':
            Content = request.POST.get('Content')
            Rating = int(request.POST.get('Rating'))

            UserReviews = Reviews.objects.filter(Profile = _Account).first()
            if UserReviews:
                UserReviews.Content = Content
                UserReviews.Rating = Rating
                UserReviews.save()
            else:
                UserReviews = Reviews.objects.create(Profile = _Account, Content = Content, Rating = Rating)
                UserReviews.save()
            return HttpResponseRedirect(reverse('Public:ReviewsPage'))
        else:
            _Reviews = Reviews.objects.filter(Profile = _Account).first()
            context = {
                "isAuthenticated": True,
                "Account": _Account,
                "Reviews": _Reviews
            }
            return render(request, 'Public/Reviews/ReviewsUpdate.html', context)
    else:
        return HttpResponseRedirect(reverse('Public:ReviewsPage'))

S3DirectWebsite/Core/templates/Public/Reviews/Reviews.html
{% extends 'Core.html' %}

{% block styleSection %}
{% endblock %}

{% block headSection %}
<link rel="stylesheet" href="/static/reviews_.css">
{% endblock %}

{% block content %}

  <!-- Forum -  
  {% if isAuthenticated %}
  You are Authenticated as {{ Account.Username }}
  {% else %}
  Not Authenticated
  {% endif %}

  <br/><br/>

  <h1>Reviews</h1>
  {% if isAuthenticated %}
  <button><a href="{% url 'Public:ReviewsUpdatePage' %}">Your Review</a></button>
  {% else %}
  <button><a href="{% url 'Authenticate:LoginPage' %}">Login to Review</a></button>
  {% endif %} -->

    
    <!-- <label for="options">Sort by:</label>
    <select id="options" onchange="window.location.href = this.value;">
        <option value="" selected disabled>Choose an option</option>
        <option value="{% url 'Public:ReviewsPage' %}?sortby=ascdate">Asc dateCreated</option>
        <option value="{% url 'Public:ReviewsPage' %}?sortby=dscdate">Dsc dateCreated</option>
        <option value="{% url 'Public:ReviewsPage' %}?sortby=ascrating">Asc Rating</option>
        <option value="{% url 'Public:ReviewsPage' %}?sortby=dscrating">Dsc Rating</option>
    </select> -->

    <!-- {% if UserReviews %}
      <hr/>
      <p>{{ UserReviews.Content }}</p>
      <p>By: {{ UserReviews.Profile.Username }}</p>
      <p>Created: {{ UserReviews.dateCreated }}</p>
      <p>Updated: {{ UserReviews.dateModified }}</p>
      <br/><br/>

      {{ UserReviews.Rating }}
      - Rating

      <hr/>
      <br/><br/>
    {% endif %} -->

    <div class="review-section">
      <div class="review-header">
          <div class="review-input">

            <form action="{% url 'Public:ReviewsUpdatePage' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}

              {% if UserReviews %}
                <input type="text" placeholder="Write a review..." class="write-review" id="content" name="Content" value="{{ UserReviews.Content }}">
              {% else %}
                <input type="text" placeholder="Write a review..." class="write-review" id="content" name="Content">
              {% endif %}

              <input type="text" id="Rating" name="Rating" required hidden value="9">

              {% if isAuthenticated %}
                <button class="submit-btn" type="submit">&#9654;</button>
              {% else %}
                <button class="submit-btn" onclick="alert('Login to post review.')">&#9654;</button>
              {% endif %}

            </form>
            
          </div>
          <select class="filter" onchange="window.location.href = this.value;">
            <option value="" selected disabled>Choose an option</option>
            <option value="{% url 'Public:ReviewsPage' %}?sortby=ascdate">Asc dateCreated</option>
            <option value="{% url 'Public:ReviewsPage' %}?sortby=dscdate">Dsc dateCreated</option>
            <option value="{% url 'Public:ReviewsPage' %}?sortby=ascrating">Asc Rating</option>
            <option value="{% url 'Public:ReviewsPage' %}?sortby=dscrating">Dsc Rating</option>
          </select>
      </div>
      <h2>Reviews from our users</h2>

      {% if UserReviews %}
        <div class="review">
          <h3>{{ UserReviews.Profile.firstName }} {{ UserReviews.Profile.lastName }}</h3>
          <p>"{{ UserReviews.Content }}"</p>
        </div>
      {% endif %}

      {% for r in Reviews %}

        <div class="review">
            <h3>{{ r.Profile.firstName }} {{ r.Profile.lastName }}</h3>
            <p>"{{ r.Content }}"</p>
        </div>

      {% empty %}
        <h4>No Reviews</h4>
      {% endfor %}

    </div>

  <!-- <div class="reviews-section">
    <h2 class="section-heading">Reviews from our users</h2>
    <div class="review-cards"> -->

      <!-- {% for r in Reviews %} -->
        <!-- <hr/>
        <p>{{ r.Content }}</p>
        <p>By: {{ post.Profile.Username }}</p>
        <p>Created: {{ post.dateCreated }}</p>
        <p>Updated: {{ post.dateModified }}</p>
        <br/><br/>

        {{ r.Rating }}
        - Rating

        <hr/>
        <br/><br/> -->

        <!-- <div class="review-card">
            <div class="review-content">
                <div class="reviewer-name">{{ r.Profile.firstName }} {{ r.Profile.lastName }}</div>
                <p class="review-text">"{{ r.Content }}"</p>
            </div>
        </div>

      {% empty %}
        <h4>No Reviews</h4>
      {% endfor %} -->

    <!-- </div>
  </div> -->

{% endblock %}

S3DirectWebsite/Core/templates/Public/Reviews/ReviewsUpdate.html
{% extends 'Core.html' %}

{% block content %}

  Forum -  
  {% if isAuthenticated %}
  You are Authenticated as {{ Account.Username }}
  {% else %}
  Not Authenticated
  {% endif %}

  <br/><br/>

  <h1>Reviews</h1>
  {% if Reviews %}
  <h4> Edit your reviews </h4>
  {% else %}
  <h4> Create your first review </h4>
  {% endif %}

  <br/>
  <form action="{% url 'Public:ReviewsUpdatePage' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">Rating:</label>
    {% if Reviews %}
    <input type="text" id="Rating" name="Rating" required value="{{ Reviews.Rating }}">
    {% else %}
    <input type="text" id="Rating" name="Rating" required>
    {% endif %}
    <br>
    <label for="content">Content:</label>
    {% if Reviews %}
    <textarea id="content" name="Content" rows="5" cols="50" required>{{ Reviews.Content }}</textarea>
    {% else %}
    <textarea id="content" name="Content" rows="5" cols="50" required></textarea>
    {% endif %}
    <br><br/>
    {% if Reviews %}
    <input type="submit" value="Update Review">
    {% else %}
    <input type="submit" value="Create Review">
    {% endif %}
  </form>

{% endblock %}