S3DirectWebsite/Authenticate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "Authenticate"
urlpatterns = [
    path("login/", auth.login, name = "LoginPage"),
    path("logout/", auth.logout, name = "LogoutPage"),
    path("create/account/", auth.createAccount, name = "CreateAccount"),
    path("account/forgot/password/", auth.forgotPassword, name = "ForgotPassword"),
]

S3DirectWebsite/Core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "Public"
urlpatterns = [
     path("", Home.home, name = "HomePageReverse"),
     path("home/", Home.home, name = "HomePage"),
     path("about/", Home.about, name = "AboutPage"),
     path("contact/", Home.contact, name = "ContactPage"),
     path("download/", Home.download, name = "DownloadPage"),

     path("forum/", Forum.forum, name = "ForumPage"),
     path("forum/create/", Forum.forumCreate, name = "ForumCreatePage"),
     path("forum/<str:slug>/", Forum.forumDetail, name = "ForumDetailPage"),
     path("forum/<str:slug>/action/", Forum.forumAction, name = "ForumActionPage"),
     path("forum/<str:slug>/edit/", Forum.forumEdit, name = "ForumEditPage"),
     path("forum/<str:slug>/delete/", Forum.forumDelete, name = "ForumDeletePage"),
     path("forum/<str:slug>/comment/", Forum.forumComment, name = "ForumAddComment"),

     path("reviews/", ReviewsC.reviewsFunc, name = "ReviewsPage"),
     path("reviews/update/", ReviewsC.reviewsUpdate, name = "ReviewsUpdatePage"),
]

S3DirectWebsite/S3DirectWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('auth/', include('Authenticate.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

S3DirectWebsite/Authenticate/models.py
from django.contrib.auth.models import User
from django.db import models
import uuid

class Account(models.Model):
    dateCreated = models.DateTimeField(auto_now_add = True)
    dateModified = models.DateTimeField(auto_now = True)
    primaryKey = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    Username = models.OneToOneField(User, on_delete=models.CASCADE)
    isActive = models.BooleanField(default=False)
    email = models.CharField(max_length=100, default="")
    firstName = models.CharField(max_length=100, default="")
    lastName = models.CharField(max_length=100, default="")

S3DirectWebsite/Authenticate/templates/Authenticate/Login.html
<!-- {% if request.GET.error %}
    <p>Error: {{ request.GET.error }}</p>
{% endif %}

<br/>

<h1>Login</h1>
<form action="{% url 'Authenticate:LoginPage' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required>
    <br><br/>
    <input type="submit" value="Login">
    <button>
        <a href="{% url 'Authenticate:CreateAccount' %}">Create Account</a>
    </button>
</form> -->


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/static/loginstyle.css">
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>

    {% if request.GET.error %}
        <p>Error: {{ request.GET.error }}</p>
    {% endif %}

    <div class="container">
        <form class="login-form" action="{% url 'Authenticate:LoginPage' %}" method="post">
            {% csrf_token %}
            <h2>Log In</h2>
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" type="text" id="username" name="username" required placeholder="Username">
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="Password">
                <a href="#" class="forgot-password">Forgot Password?</a>
            </div>
            <div class="input-group remember-me">
                <input type="checkbox" id="remember">
                <label for="remember">Remember me?</label>
            </div>
            <button type="submit" class="primary-button">LOG IN</button>
            <p class="switch">Don't have an account? <br><a href="{% url 'Authenticate:CreateAccount' %}">Create an account</a></p>
        </form>
    </div>
</body>

</html>

S3DirectWebsite/Authenticate/templates/Authenticate/createAccount.html
<!-- <br/>

<h1>Create Account</h1>
<form action="{% url 'Authenticate:CreateAccount' %}" method="post">
{% csrf_token %}
<label for="firstname">Firstname:</label>
  <input type="text" id="firstname" name="firstname" required>
  <br>
  <label for="lastname">Lastname:</label>
  <input type="text" id="lastname" name="lastname" required>
  <br>
  <label for="username">Username:</label>
  <input type="text" id="username" name="username" required>
  <br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="email" required>
  <br>
  <label for="password">Password:</label>
  <input type="password" id="password" name="password" required>
  <br>
  <label for="confirmPassword">Confirm Password:</label>
  <input type="password" id="confirmPassword" name="confirmPassword" required>
  <br>
  <input type="submit" value="Create Account">
</form>
<a href="{% url 'Authenticate:LoginPage' %}">Login</a> -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="/static/loginstyle.css">
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>

  
{% if request.GET.error %}
<p>Error: {{ request.GET.error }}</p>
{% endif %}

    <div class="container">
        <form class="login-form" action="{% url 'Authenticate:CreateAccount' %}" method="post">
          {% csrf_token %}
            <h2>Create Account</h2>
            <div class="input-group">
              <label for="username">Username</label>
              <input type="text" id="username" name="username" placeholder="Username">
          </div>
          <div class="input-group">
            <label for="firstname">Firstname</label>
            <input type="text" id="firstname" name="firstname" required placeholder="Firstname">
          </div>
          <div class="input-group">
            <label for="lastname">Lastname</label>
            <input type="text" id="lastname" name="lastname" required placeholder="Lastname">
          </div>
            <div class="input-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" placeholder="Email">
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="Password">
            </div>
            <div class="input-group">
              <label for="password">Confirm Password</label>
              <input type="password" id="confirmPassword" name="confirmPassword" required placeholder="Confirm Password">
            </div>
            <button type="submit" class="primary-button">SIGN UP</button>
            <p class="switch">Already have an account? <br><a href="{% url 'Authenticate:LoginPage' %}">Log In</a></p>
        </form>
    </div>
</body>

</html>